# Generated by Django 5.0.3 on 2024-03-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pronduit', models.CharField(max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=100)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
