# Generated by Django 5.0.3 on 2024-03-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0003_alter_produit_prix'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produit',
            new_name='ProduitDeal',
        ),
    ]
