# Generated by Django 5.0.3 on 2024-03-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0005_topproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topproducts',
            name='image',
            field=models.ImageField(upload_to='static/topimages/'),
        ),
    ]
