# Generated by Django 5.0.3 on 2024-03-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0008_alter_produitdeal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grilles',
            name='images',
            field=models.ImageField(default='default_image.jpg', upload_to='media/Grille/'),
        ),
    ]
