# Generated by Django 5.0.3 on 2024-03-23 18:36

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0010_produitdeal_slug_topproducts_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitdeal',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='topproducts',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, max_length=2000, null=True),
        ),
    ]
