# Generated by Django 5.0.3 on 2024-03-23 18:38

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0011_alter_produitdeal_slug_alter_topproducts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitdeal',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name_produit'),
        ),
        migrations.AlterField(
            model_name='topproducts',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name_produit'),
        ),
    ]
