# Generated by Django 5.0.3 on 2024-03-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0015_produitdeal_image_detail_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topproducts',
            name='stock',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
