# Generated by Django 5.0.3 on 2024-03-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0017_produitdeal_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitdeal',
            name='detail',
            field=models.TextField(default='Disponible', max_length=100000000, null=True),
        ),
        migrations.AlterField(
            model_name='topproducts',
            name='stock',
            field=models.CharField(default='Disponible', max_length=200, null=True),
        ),
    ]
