# Generated by Django 5.0.3 on 2024-03-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0018_alter_produitdeal_detail_alter_topproducts_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topproducts',
            name='stock',
            field=models.CharField(default='Disponible', max_length=200),
        ),
    ]
