# Generated by Django 5.0.3 on 2024-03-24 12:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0021_alter_topproducts_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produitdeal',
            old_name='name_pronduit',
            new_name='name_produit',
        ),
        migrations.AlterField(
            model_name='produitdeal',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name_produit'),
        ),
    ]
